name: Build and Release WAR File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: "Release-Test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get the version from pom.xml
        id: get_version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Identify WAR file
        id: find_war
        run: echo "WAR_PATH=$(ls target/*.war)" >> $GITHUB_ENV

      - name: Upload WAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_${{ env.RELEASE_VERSION }}
          path: ${{ env.WAR_PATH }}

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.RELEASE_VERSION }}"
          draft: true
          title: "${{ env.ARTIFACT_NAME }} v${{ env.RELEASE_VERSION }}"
          files: |
            ${{ env.WAR_PATH }}