name: Build and Release WAR File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get the version from pom.xml
        id: get_version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Archive WAR file
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: target/*.war

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo apt update
          sudo apt install gh

      - name: Create Release and Upload Asset
        run: |
          gh release create ${{ env.RELEASE_VERSION }} ./target/*.war --notes "Release version ${{ env.RELEASE_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}